version: '3'
services:
  db:
    image: postgres
    networks:
      - database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - ./back/database/data/prod:/var/lib/postgresql/data/
    restart: always
    container_name: db
  # back:
  #   build:
  #     context: ./back
  #     dockerfile: Dockerfile
  #   depends_on: 
  #     - db
  #   networks:
  #     - webapp
  #     - database
  #   ports:
  #     - 5500:5500
  #   volumes:
  #     - ./back/node_modules:/app/node_modules
  #     - ./back/src:/app/src
  #   depends_on:
  #     - db
  #   restart: always
  #   command: ['./wait-for-it.sh', 'db:5432', '--', 'node', 'main.js']
  #   container_name: back
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    # depends_on: 
    #   - back
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
    networks:
      - webapp
    ports:
      - 8080:3000
    stdin_open: true
    restart: always
    container_name: front

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
